// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.quick.dfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\032com.quick.dfs" +
      ".namenode.rpc\032\026NameNodeRpcModel.proto2\245\010" +
      "\n\017NameNodeService\022e\n\010register\022+.com.quic" +
      "k.dfs.namenode.rpc.RegisterRequest\032,.com" +
      ".quick.dfs.namenode.rpc.RegisterResponse" +
      "\022h\n\theartbeat\022,.com.quick.dfs.namenode.r" +
      "pc.HeartbeatRequest\032-.com.quick.dfs.name" +
      "node.rpc.HeartbeatResponse\022\\\n\005mkDir\022(.co" +
      "m.quick.dfs.namenode.rpc.MkDirRequest\032)." +
      "com.quick.dfs.namenode.rpc.MkDirResponse",
      "\022e\n\010shutdown\022+.com.quick.dfs.namenode.rp" +
      "c.ShutdownRequest\032,.com.quick.dfs.nameno" +
      "de.rpc.ShutdownResponse\022q\n\014fetchEditLog\022" +
      "/.com.quick.dfs.namenode.rpc.FetchEditLo" +
      "gRequest\0320.com.quick.dfs.namenode.rpc.Fe" +
      "tchEditLogResponse\022\211\001\n\024updateCheckpointT" +
      "xid\0227.com.quick.dfs.namenode.rpc.UpdateC" +
      "heckpointTxidRequest\0328.com.quick.dfs.nam" +
      "enode.rpc.UpdateCheckpointTxidResponse\022k" +
      "\n\ncreateFile\022-.com.quick.dfs.namenode.rp",
      "c.CreateFileRequest\032..com.quick.dfs.name" +
      "node.rpc.CreateFileResponse\022\200\001\n\021allocate" +
      "DataNodes\0224.com.quick.dfs.namenode.rpc.A" +
      "llocateDataNodesRequest\0325.com.quick.dfs." +
      "namenode.rpc.AllocateDataNodesResponse\022\214" +
      "\001\n\025informReplicaReceived\0228.com.quick.dfs" +
      ".namenode.rpc.InformReplicaReceivedReque" +
      "st\0329.com.quick.dfs.namenode.rpc.InformRe" +
      "plicaReceivedResponseB6\n\"com.quick.dfs.n" +
      "amenode.rpc.serviceB\016NameNodeServerP\001b\006p",
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.quick.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.quick.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
