// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.quick.dfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\032com.quick.dfs" +
      ".namenode.rpc\032\026NameNodeRpcModel.proto2\300\002" +
      "\n\017NameNodeService\022e\n\010register\022+.com.quic" +
      "k.dfs.namenode.rpc.RegisterRequest\032,.com" +
      ".quick.dfs.namenode.rpc.RegisterResponse" +
      "\022h\n\theartbeat\022,.com.quick.dfs.namenode.r" +
      "pc.HeartbeatRequest\032-.com.quick.dfs.name" +
      "node.rpc.HeartbeatResponse\022\\\n\005mkDir\022(.co" +
      "m.quick.dfs.namenode.rpc.MkDirRequest\032)." +
      "com.quick.dfs.namenode.rpc.MkDirResponse",
      "B6\n\"com.quick.dfs.namenode.rpc.serviceB\016" +
      "NameNodeServerP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.quick.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.quick.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
