// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public interface FetchEditLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quick.dfs.namenode.rpc.FetchEditLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional int64 syncedTxid = 2;</code>
   */
  long getSyncedTxid();
}
