// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public interface GetDataNodeForFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quick.dfs.namenode.rpc.GetDataNodeForFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string fileName = 1;</code>
   */
  String getFileName();
  /**
   * <code>optional string fileName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
