// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public interface GetDataNodeForFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quick.dfs.namenode.rpc.GetDataNodeForFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>optional string dataNodeInfo = 2;</code>
   */
  String getDataNodeInfo();
  /**
   * <code>optional string dataNodeInfo = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataNodeInfoBytes();
}
