// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_MkDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_MkDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_MkDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_MkDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_FetchEditLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_FetchEditLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_FetchEditLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_FetchEditLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022\032com.quick.dfs." +
      "namenode.rpc\"/\n\017RegisterRequest\022\n\n\002ip\030\001 " +
      "\001(\t\022\020\n\010hostname\030\002 \001(\t\"\"\n\020RegisterRespons" +
      "e\022\016\n\006status\030\001 \001(\005\"0\n\020HeartbeatRequest\022\n\n" +
      "\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"5\n\021Heartbeat" +
      "Response\022\016\n\006status\030\001 \001(\005\022\020\n\010commands\030\002 \001" +
      "(\t\"\034\n\014MkDirRequest\022\014\n\004path\030\001 \001(\t\"\037\n\rMkDi" +
      "rResponse\022\016\n\006status\030\001 \001(\005\"\037\n\017ShutdownReq" +
      "uest\022\014\n\004code\030\001 \001(\005\"\"\n\020ShutdownResponse\022\016" +
      "\n\006status\030\001 \001(\005\"7\n\023FetchEditLogRequest\022\014\n",
      "\004code\030\001 \001(\005\022\022\n\nsyncedTxid\030\002 \001(\003\"8\n\024Fetch" +
      "EditLogResponse\022\016\n\006status\030\001 \001(\005\022\020\n\010editL" +
      "ogs\030\002 \001(\t\"+\n\033UpdateCheckpointTxidRequest" +
      "\022\014\n\004txid\030\001 \001(\003\".\n\034UpdateCheckpointTxidRe" +
      "sponse\022\016\n\006status\030\001 \001(\005\"%\n\021CreateFileRequ" +
      "est\022\020\n\010fileName\030\001 \001(\t\"$\n\022CreateFileRespo" +
      "nse\022\016\n\006status\030\001 \001(\005\">\n\030AllocateDataNodes" +
      "Request\022\020\n\010fileName\030\001 \001(\t\022\020\n\010fileSize\030\002 " +
      "\001(\003\".\n\031AllocateDataNodesResponse\022\021\n\tdata" +
      "Nodes\030\001 \001(\t\"N\n\034InformReplicaReceivedRequ",
      "est\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\020\n\010fil" +
      "eName\030\003 \001(\t\"/\n\035InformReplicaReceivedResp" +
      "onse\022\016\n\006status\030\001 \001(\005\"k\n ReportCompleteSt" +
      "orageInfoRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname" +
      "\030\002 \001(\t\022\021\n\tfileNames\030\003 \001(\t\022\026\n\016storedDataS" +
      "ize\030\004 \001(\003\"3\n!ReportCompleteStorageInfoRe" +
      "sponse\022\016\n\006status\030\001 \001(\005\"-\n\031GetDataNodeFor" +
      "FileRequest\022\020\n\010fileName\030\001 \001(\t\"B\n\032GetData" +
      "NodeForFileResponse\022\016\n\006status\030\001 \001(\005\022\024\n\014d" +
      "ataNodeInfo\030\002 \001(\tB6\n com.quick.dfs.namen",
      "ode.rpc.modelB\020NameNodeRpcModelP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_quick_dfs_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_quick_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_RegisterRequest_descriptor,
        new String[] { "Ip", "Hostname", });
    internal_static_com_quick_dfs_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_quick_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_RegisterResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_quick_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_HeartbeatRequest_descriptor,
        new String[] { "Ip", "Hostname", });
    internal_static_com_quick_dfs_namenode_rpc_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_quick_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_HeartbeatResponse_descriptor,
        new String[] { "Status", "Commands", });
    internal_static_com_quick_dfs_namenode_rpc_MkDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_quick_dfs_namenode_rpc_MkDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_MkDirRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_quick_dfs_namenode_rpc_MkDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_quick_dfs_namenode_rpc_MkDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_MkDirResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_quick_dfs_namenode_rpc_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_ShutdownRequest_descriptor,
        new String[] { "Code", });
    internal_static_com_quick_dfs_namenode_rpc_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_quick_dfs_namenode_rpc_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_ShutdownResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_FetchEditLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_quick_dfs_namenode_rpc_FetchEditLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_FetchEditLogRequest_descriptor,
        new String[] { "Code", "SyncedTxid", });
    internal_static_com_quick_dfs_namenode_rpc_FetchEditLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_quick_dfs_namenode_rpc_FetchEditLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_FetchEditLogResponse_descriptor,
        new String[] { "Status", "EditLogs", });
    internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor,
        new String[] { "Txid", });
    internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_quick_dfs_namenode_rpc_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_CreateFileRequest_descriptor,
        new String[] { "FileName", });
    internal_static_com_quick_dfs_namenode_rpc_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_quick_dfs_namenode_rpc_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_CreateFileResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor,
        new String[] { "FileName", "FileSize", });
    internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor,
        new String[] { "DataNodes", });
    internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor,
        new String[] { "Ip", "Hostname", "FileName", });
    internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor,
        new String[] { "Ip", "Hostname", "FileNames", "StoredDataSize", });
    internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileRequest_descriptor,
        new String[] { "FileName", });
    internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quick_dfs_namenode_rpc_GetDataNodeForFileResponse_descriptor,
        new String[] { "Status", "DataNodeInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
