// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public interface RelocateDataNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quick.dfs.namenode.rpc.RelocateDataNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string dataNode = 1;</code>
   */
  String getDataNode();
  /**
   * <code>optional string dataNode = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataNodeBytes();
}
