// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public interface RelocateDataNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quick.dfs.namenode.rpc.RelocateDataNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string fileName = 1;</code>
   */
  String getFileName();
  /**
   * <code>optional string fileName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>optional int64 fileSize = 2;</code>
   */
  long getFileSize();

  /**
   * <code>optional string excludeDataNodes = 3;</code>
   */
  String getExcludeDataNodes();
  /**
   * <code>optional string excludeDataNodes = 3;</code>
   */
  com.google.protobuf.ByteString
      getExcludeDataNodesBytes();
}
