// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.quick.dfs.namenode.rpc.model;

public interface ReportCompleteStorageInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quick.dfs.namenode.rpc.ReportCompleteStorageInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   */
  String getIp();
  /**
   * <code>optional string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string hostname = 2;</code>
   */
  String getHostname();
  /**
   * <code>optional string hostname = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>optional string fileNames = 3;</code>
   */
  String getFileNames();
  /**
   * <code>optional string fileNames = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileNamesBytes();

  /**
   * <code>optional int64 storedDataSize = 4;</code>
   */
  long getStoredDataSize();
}
